### ISSUE TITLE
Error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by sagitter** [ampl/mp#108]
Hi all.

`mp-3.1.0` does not compile on `Fedora 26` (development branch) with following error:

```
/builddir/build/BUILD/mp-3.1.0/include/mp/format.h: In member function 'void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int)':
/builddir/build/BUILD/mp-3.1.0/include/mp/format.h:1750:20: error: expected unqualified-id before numeric constant
     const unsigned CHAR_WIDTH = 1;
                    ^
```
GCC 6.2.1
Full build log: http://koji.fedoraproject.org/koji/getfile?taskID=16453533&name=build.log

**Comment by vitaut** [comment]
Caused by https://github.com/fmtlib/fmt/issues/398.

**Comment by sagitter** [comment]
Sorry, i don't understand: `mp` does not require `fmt` for compiling.

**Comment by vitaut** [comment]
It includes fmt: https://github.com/ampl/mp/blob/master/include/mp/format.h. @fdabrandao, could you update the fmt version used here?

**Comment by sagitter** [comment]
Can `mp` work with [fmt](http://koji.fedoraproject.org/koji/buildinfo?buildID=818181) from Fedora?

**Comment by vitaut** [comment]
The goal is to have `mp` self-contained, but it's possible to add a macro to control this. I'm no longer working on this project though, just wanted to point out a fix.

**Comment by fdabrandao** [comment]
Thank you for reporting this issue, @sagitter. And thank you @vitaut for pointing out the fix. I have just updated fmt version to 3.0.1 so the problem should be fixed. It took a lot longer than expected because of a few very long compile errors in code related to ilogcp that appeared with the update.

**Comment by sagitter** [comment]
Thanks.
