### ISSUE TITLE
Some header files are not installed

### ISSUE THREAD

**Issue by dpo** [ampl/mp#110]
The following header files in `src/asl/solvers` are not installed by `make install`. I wonder if that's intentional or an omission? Certain solver interfaces require some of them:
```
errchk.h
jac2dim.h
obj_adj.h
```
Thanks.

**Comment by fdabrandao** [comment]
Thanks for reporting this issue. It should have been fixed in 8183be3e486d38d281e0c5a02a1ea4239695035e. Please let me know if the problem persists.

**Comment by dpo** [comment]
Thank you!
