### ISSUE TITLE
CMake failure on clean checkout

### ISSUE THREAD

**Issue by PetterS** [ampl/mp#118]
I am running the following commands on Linux:

    git clone https://github.com/ampl/mp.git
    mkdir mp-build && cd mp-build
    cmake ../mp

And I get the following output:

    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    [...]
    -- Configuring done
    CMake Error at test/tables/CMakeLists.txt:61 (add_dependencies):
      The dependency target "ampltabl" of target "tableproxy-test" does not
      exist.

    -- Generating done
    -- Build files have been written to: /usr/local/google/home/strandmark/source/mp-build

The cmake (3.9.0) command returns failure (and trying make afterwards fails).

I have also tried Windows and WSL with no luck.

**Comment by fdabrandao** [comment]
A test to avoid this error message has been added in 99f830f0560e2062a9ac6a82e68269acc9e3021f. Previously it was necessary to run cmake with the option "-DBUILD=all" ("cmake -DBUILD=all .") in order to build all modules including ampltabl, which is not being built by default.
