### ISSUE TITLE
Make failure: 'funcadd.h' file not found

### ISSUE THREAD

**Issue by LiyuanCao** [ampl/mp#119]
I tried

> git clone https://github.com/ampl/mp.git
mkdir mp-build && cd mp-build
cmake ../mp

and so far so good. Then I typed `make` and it failed after 23%:

> Scanning
 dependencies of target format
[  1%] Building CXX object CMakeFiles/format.dir/src/format.cc.o
[  2%] Building CXX object CMakeFiles/format.dir/src/posix.cc.o
[  2%] Built target format
Scanning dependencies of target gen-expr-info
[  3%] Building CXX object CMakeFiles/gen-expr-info.dir/src/gen-expr-info.cc.o
[  4%] Linking CXX executable bin/gen-expr-info
[  4%] Built target gen-expr-info
[  5%] Generating /Users/liyuancao/Google Drive/2018summer/dfmoo18/code/AMPL2Matlab/mp/src/expr-info.cc
Scanning dependencies of target mp
[  7%] Building CXX object CMakeFiles/mp.dir/src/clock.cc.o
[  8%] Building CXX object CMakeFiles/mp.dir/src/expr.cc.o
[  9%] Building CXX object CMakeFiles/mp.dir/src/nl-reader.cc.o
[ 10%] Building CXX object CMakeFiles/mp.dir/src/option.cc.o
[ 11%] Building CXX object CMakeFiles/mp.dir/src/os.cc.o
[ 12%] Building CXX object CMakeFiles/mp.dir/src/problem.cc.o
[ 14%] Building CXX object CMakeFiles/mp.dir/src/rstparser.cc.o
[ 15%] Building CXX object CMakeFiles/mp.dir/src/sol.cc.o
[ 16%] Building CXX object CMakeFiles/mp.dir/src/solver.cc.o
[ 17%] Building CXX object CMakeFiles/mp.dir/src/sp.cc.o
[ 18%] Building CXX object CMakeFiles/mp.dir/src/expr-info.cc.o
[ 20%] Linking CXX static library lib/libmp.a
[ 20%] Built target mp
Scanning dependencies of target nl-example
[ 21%] Building CXX object CMakeFiles/nl-example.dir/src/nl-example.cc.o
[ 22%] Linking CXX executable bin/nl-example
[ 22%] Built target nl-example
Scanning dependencies of target cp
[ 23%] Building CXX object src/cp/CMakeFiles/cp.dir/cp.cc.o
/Users/liyuancao/Google Drive/2018summer/dfmoo18/code/AMPL2Matlab/mp/src/cp/cp.cc:27:10: fatal error: 
      'funcadd.h' file not found
#include "funcadd.h"
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/cp/CMakeFiles/cp.dir/cp.cc.o] Error 1
make[1]: *** [src/cp/CMakeFiles/cp.dir/all] Error 2
make: *** [all] Error 2

Seems like funcadd.h is missing.

**Comment by JasonZhou404** [comment]
I found the same issue. No clue.

**Comment by mingodad** [comment]
The problem seems they forgot to mention on the readme that we need to issue git submodule init & git submodule update & cmake -DBUILD=all 
```
git clone https://github.com/ampl/mp.git
cd mp
git submodule init
git submodule update
mkdir build         # Create a directory to hold the build output.
cd build
cmake -DBUILD=all <path/to/mp>  # Generate native build scripts.
```
Cheers !

**Comment by fdabrandao** [comment]
Thanks for help @mingodad! The README has just been updated with all the steps from cloning to generating native build scripts.
