### ISSUE TITLE
Strange behavior of -= option on windows

### ISSUE THREAD

**Issue by mapgccv** [ampl/mp#138]
Executing ```gurobidirect -=``` on windows gives an erratic output: some options are not printed or half printed, as well as the header.
Setting a breakpoint in the ```SolverAppOptionParser::ShowSolverOptions``` function and stepping through it with the debugger seems to be fixing it. @glebbelov , can you see whether this happens on Linux too?

**Comment by glebbelov** [comment]
Not on Linux. Guess it's something about fmt library but not sure. No idea otherwise

**Comment by mapgccv** [comment]
A bit more investigation let me to find the culprit:
Windows 11 option to assign the default console host to the new Terminal app creates the problem; when Visual Studio creates the terminal window, some of the output gets scrambled. It does not happen executing the solver directly from cmd or from Windows terminal, nor executing it via Visual Studio on the normal console host.
