### ISSUE TITLE
FreeBSD: Fix compilation issue

### ISSUE THREAD

**Issue by Mizux** [ampl/mp#143]
## Context
When building for FreeBSD [google/or-tools](https://github.com/google/or-tools) which compile [scipopt/scip](https://github.com/scipopt/scip) which compile ampl/mp we have an error due to this line:

https://github.com/ampl/mp/blob/c987ff23168964dcc4b9c3317dd034f95e4c9b2d/src/os.cc#L107-L109

## Observed
When compiling SCIP (which contains ampl/mp "source")
```sh
default: [ 48%] Building CXX object _deps/scip-build/src/CMakeFiles/libscip.dir/amplmp/src/os.cpp.o
    default: cd /usr/home/vagrant/project/build/_deps/scip-build/src && /usr/bin/c++  -I/usr/home/vagrant/project/build/_deps/scip-src/src/amplmp/include -I/usr/home/vagrant/project/build/_deps/scip-build -I/usr/home/vagrant/project/build/_deps/scip-src/src -I/usr/home/vagrant/project/build/_deps/zlib-build -I/usr/home/vagrant/project/build/_deps/zlib-src -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++14 -MD -MT _deps/scip-build/src/CMakeFiles/libscip.dir/amplmp/src/os.cpp.o -MF CMakeFiles/libscip.dir/amplmp/src/os.cpp.o.d -o CMakeFiles/libscip.dir/amplmp/src/os.cpp.o -c /usr/home/vagrant/project/build/_deps/scip-src/src/amplmp/src/os.cpp
    default: /usr/home/vagrant/project/build/_deps/scip-src/src/amplmp/src/os.cpp:108:4: error: GetExecutablePath is not implemented for this system
    default: #  error GetExecutablePath is not implemented for this system
    default:    ^
    default: 1 error generated.
    default: *** Error code 1
```

## Expected
build pass

## Proposal
2min googling around:
https://fossies.org/linux/sccs/libschily/getexecpath.c seems to be a good starting point ;)

## Releated issue
* https://github.com/google/or-tools/issues/2783
* https://github.com/scipopt/scip/issues/7

**Comment by glebbelov** [comment]
@Mizux should be fixed, have not checked it (it takes a while to install FreeBSD), please check
