### ISSUE TITLE
if-then-else expression with a variable in the "if" condition

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#148]
An inexperienced user wanted to express "when T[i]<=0, F[i]=0; when T[i]>0, F[i]=1" where T[i] was an integer variable and F[i] was a binary variable. He came up with this, which is correct but not currently accepted by any MIP solver interface:
```
var T{I} integer;
var F{I} >= 0 binary;
subject to C8 {i in I}: F[i] = (if T[i] <= 0 then 0 else 1);
```
I don't recall seeing that this will be accepted by the new MP interface, and if not, maybe it's something to put on a wish list for future versions. (Currently, the best approach is to rewrite it as an indicator constraint.)

**Comment by glebbelov** [comment]
If-then with constants works already: [assign1.mod](https://github.com/ampl/mp/blob/feature/direct_interface/test/end2end/cases/categorized/cp_global_constraints/assign1.mod)

Most meaningful for this example is the equivalence operator:
```
F[i] <==> (T[i] >= 1)
```
