### ISSUE TITLE
Glitches in x-gurobi solve message

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#158]
With no options set, the first line of the x-gurobi solve message does not come out right:
```
ampl: model diet.mod;
ampl: data diet.dat;
ampl: option solver x-gurobi;
ampl: solve;
Gurobi 9.5.0: Set paramGurobi 9.5.0: optimal solution; objective 88.2
1 simplex iterations
ampl: 
```
This is a side-effect of the unwanted appearance of `Set parameter Username` at the beginning of the Gurobi run.

**Comment by glebbelov** [comment]
This works fine on Linux. Looking on Windows

**Comment by glebbelov** [comment]
@4er4er4er I cannot reproduce this on Linux with compiled executables, or on Windows with compiled and bundled executables. Please provide your setup

**Comment by 4er4er4er** [comment]
For my example I ran under Windows, using the sw.exe utility (provided in our Windows AMPL distribution for use in installation and troubleshooting). The Gurobi message is different if I use a Windows command prompt window, so here's a complete Windows comparison.

In sw.exe:
```
gurobi:

ampl: solve;
Set parameter Username
Gurobi 9.5.0: optimal solution; objective 88.2
1 simplex iterations
ampl: 

x-gurobi:

ampl: solve;
Gurobi 9.5.0: Set paramGurobi 9.5.0: optimal solution; objective 88.2
1 simplex iterations
ampl: 
```
In the command prompt window:
```
gurobi:

ampl: solve;
Gurobi 9.5.0: Set parameter Username
optimal solution; objective 88.2
1 simplex iterations
ampl:

x-gurobi:

ampl: solve;
Gurobi 9.5.0: Set parameter Username
Gurobi 9.5.0: optimal solution; objective 88.2
1 simplex iterations
ampl:
```
Curiously, no two are the same. The sw.exe x-gurobi case is the only one that has seriously garbled output, but all are affected to some extent by Gurobi 9.5's superfluous "Set parameter Username" message. In contrast, under previous versions of Gurobi, there is the same 2-line message when using either sw.exe or the command prompt window:
```
ampl: solve;
Gurobi 9.1.2: optimal solution; objective 88.2
1 simplex iterations
ampl:
```
So far we have not figured out a way to get rid of "Set parameter Username" in 9.5, so we may have to consider adding a hack to deal with it in sw.exe.
