### ISSUE TITLE
Use develop branch

### ISSUE THREAD

**Issue by glebbelov** [ampl/mp#172]
Instead of feature/direct-interface.

Moreover, in Contributing Guide, advise to clone develop

**Comment by mapgccv** [comment]
Yep, I agree. Should we just delete the develop branch and rename feature/direct-interface to develop?

**Comment by glebbelov** [comment]
I remember GitLab did not allow using the names of deleted branches. As develop is just an old version of master, I seem to have merged feature/ there. I'll be keeping both branches in  sync. Let me know if I can help update the CI/docu, then we can retire the feature/ branch.

**Comment by fdabrandao** [comment]
The documentation is now configured to follow the develop branch instead of feature/direct-interface.
