### ISSUE TITLE
Changes for ampl/mp rpm package for Fedora

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#19]
* Build shared libraries (done in https://github.com/ampl/mp/commit/ad39ca023bd82df38bc93d04e8b32e60a451784a)
* Use installed version of GSL if available

**Comment by vitaut** [comment]
@pcpa, now that the issue with Gecode has been resolved, is there anything else that needs to be done here? Otherwise I'm going to release version 1.3.0.

**Comment by pcpa** [comment]
@vitaut sorry for the delay. I do not have any pending issues, and would be fine with 1.3.0 being release now. I will actually also use it for the official Fedora review request.

**Comment by vitaut** [comment]
Done: https://github.com/ampl/mp/releases/tag/1.3.0. Thanks @pcpa for your work on packaging and feel free to open another issue (or reopen this one) if you have any problems. Closing for now.

**Comment by pcpa** [comment]
Package is now available in Fedora. For the moment only for rawhide.
http://pkgs.fedoraproject.org/cgit/mp.git/
I did need to add a patch to finish the arm build, and it may be
required to other architectures:
http://pkgs.fedoraproject.org/cgit/mp.git/diff/mp-arm.patch?id=95f0b59ae66eb4c870f4a3110a3362cd83fb4344

**Comment by vitaut** [comment]
I've applied the patch in https://github.com/ampl/mp/commit/50b284eb4e0f5be983042d535fc39ab6b7eaa94c. Thanks!
