### ISSUE TITLE
unexpected Error: unsupported: ==>

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#193]
An unexpected error is seen when sending the following model to (at least) x-Gurobi 10.0.0, x-COPT 5.0.1, and HiGHS 1.2.2, while ASL-based solvers report no error and return a feasible solution:
```
set NS;
set F2 {NS};
set NC;

var X_F2 {s in NS, F2[s], NS, NC};
var U_F2 {s in NS} = sum {v in F2[s], i in NC} X_F2[s,v,s,i];
var VAL_U_F2 {s in NS} binary;

subject to Contrainte_64 {s in NS}:
   VAL_U_F2[s] = 1  ==>  U_F2[s] >= 0.0001  else  U_F2[s] = 0;
```
For example, with this data,
```
set NS := A B C ;
set F2[A] := A1 A3 A4 ;
set F2[B] := B1 B4 ;
set F2[C] := C3 C4 C5 C7 ;
set NC := 11 22 ;
```
the MP version of Gurobi reports:
```
ampl: option solver gurobi;
ampl: solve;
x-Gurobi 10.0.0: Error: unsupported: ==>
exit value 1
<BREAK>
ampl: 
```
The error message is the same for COPT or HiGHS. The ASL-based solvers seem to handle this correctly; for instance:
```
ampl: option solver cplex;
ampl: solve;
CPLEX 20.1.0.0: optimal integer solution; objective 0
0 MIP simplex iterations
0 branch-and-bound nodes
Objective = find a feasible point.
ampl: option solver xpress;
ampl:
```

**Comment by glebbelov** [comment]
Fixed. "C ==> A else B" is flattened as an ImplicationConstraint. For MIP it is redefined as (!C or A) and (C or B).

Can be used conditionally in other expressions, e.g.:

```
x + y >= 2 ||
    (x - y >= -2 ==> y + 2*z <= -15 else x - z == 4);
```

see [test case](https://github.com/ampl/mp/blob/123426b963e37a0ef893f8f11f84e55a1a9923a0/test/end2end/cases/categorized/fast/logical/impl_else_02.mod#L13).
