### ISSUE TITLE
No outlev=1 output from Gurobi 10.0.1

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#202]
Gurobi option `outlev=1` is not producing the expected log listing:
```
ampl: model diet.mod;
ampl: data diet.dat;
ampl: option solver gurobi;
ampl: option gurobi_options 'outlev=1';
ampl: solve;
Gurobi 10.0.1: tech:outlev=1
Gurobi 10.0.1: optimal solution; objective 88.2
1 simplex iterations
ampl: 
```
This behavior was not seen in the MP version of Gurobi 10.0.0:
```
ampl: model diet.mod;
ampl: data diet.dat;
ampl: option solver gurobi;
ampl: option gurobi_options 'outlev=1';
ampl: solve;
Gurobi 10.0.0: Set parameter OutputFlag to value 1
Set parameter InfUnbdInfo to value 1
Gurobi Optimizer version 10.0.0 build v10.0.0rc2 (win64)

CPU model: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads

Optimize a model with 4 rows, 12 columns and 35 nonzeros
Model fingerprint: 0x109e1beb
Coefficient statistics:
  Matrix range     [1e+00, 7e+01]
  Objective range  [2e+00, 3e+00]
  Bounds range     [1e+02, 9e+03]
  RHS range        [1e+04, 1e+04]
Presolve time: 0.00s
Presolved: 4 rows, 12 columns, 35 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   5.468750e+01   0.000000e+00      0s
       1    8.8200000e+01   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.00 seconds (0.00 work units)
Optimal objective  8.820000000e+01
tech:outlev=1
Gurobi 10.0.0: optimal solution; objective 88.2
1 simplex iterations
ampl: 
```
Also this behavior is not seen in the ASL version of Gurobi 10.0.1, which gives a listing very similar to the one above.

**Comment by glebbelov** [comment]
This was connected to the solvers-private driver setting in gurobi_c.c:

```
	error = GRBsetintparam(*envP, "OutputFlag", 0);
```

However changing this to 1, I saw

```
ampl: solve;
Gurobi 10.0.1: Set parameter Username
Set parameter GURO_PAR_ISVKEY
Set parameter GURO_PAR_ISVNAME
Set parameter GURO_PAR_ISVAPPNAME
Set parameter LogToConsole to value 1
tech:outlev=1
........
```

The GURO_PAR_... lines appeared then even with outlev=0.

Gurobi docu says OutputFlag controls both logging to file and to console, and LogToConsole only console. MP uses LogToCOnsole for outlev, but the solvers-private MP driver sets OutputFlag=0. ASL driver only uses OutputFlag. 

The ASL driver now also printed the GURO_PAR_... lines with outlev=1, BUT not when adding option `version`. MP driver printed them always.  The pure-MP MP driver logs correctly but it probably does not set those params.

A problem was, gurobi_c.c is used by both the MP and ASL drivers. I pushed 2 fixes. The first fixes the problem for MP by switching from OutputFlag to LogToConsole in gurobi_c.c. But then, the ASL driver stopped logging. The 2nd fix-fix restores LogToConsole in ASL driver after GRBstartenv(), but now it always prints

```
Gurobi 10.0.1: Set parameter LogToConsole to value 1
```
