### ISSUE TITLE
Error at _cmdno 4952 executing "solve" command  (file r4.run, line 5, offset 65):  can't open at32480.sol 

### ISSUE THREAD

**Issue by Anastasialiyu** [ampl/mp#215]
Run the. m file using Matlab, which contains ! ampl r4. run, result appears

Error at_ Cmdno 4952 executing "solve" command

(file r4. run, line 5, offset 65):

Can't open at32480.sol
At the beginning, there was no problem, but some changes to M4.mod caused such problems
The constraints of the original mod file:
s.t. eq_PPPoutsideABCD {i in {1..Nfe}, pp in {1..Nv}, nn in {1..Nobs}, jj in {1..4}}:
abs((AX[i,pp] - PPP[nn,jj,1])*(BY[i,pp] - PPP[nn,jj,2]) - (AY[i,pp] - PPP[nn,jj,2])*(BX[i,pp] - PPP[nn,jj,1])) * 0.5 + abs((BX[i,pp] - PPP[nn,jj,1])*(CY[i,pp] - PPP[nn,jj,2]) - (BY[i,pp] - PPP[nn,jj,2])*(CX[i,pp] - PPP[nn,jj,1])) * 0.5 + abs((CX[i,pp] - PPP[nn,jj,1])*(DY[i,pp] - PPP[nn,jj,2]) - (CY[i,pp] - PPP[nn,jj,2])*(DX[i,pp] - PPP[nn,jj,1])) * 0.5 + abs((DX[i,pp] - PPP[nn,jj,1])*(AY[i,pp] - PPP[nn,jj,2]) - (DY[i,pp] - PPP[nn,jj,2])*(AX[i,pp] - PPP[nn,jj,1])) * 0.5 >= 4 + 0.1;

s.t. eq_AoutsidePRECTANGLEPPP {i in {1..Nfe}, pp in {1..Nv}, nn in {1..Nobs}}:
abs((PPP[nn,1,1] - AX[i,pp])*( PPP[nn,2,2] - AY[i,pp]) - (PPP[nn,1,2] - AY[i,pp])*(PPP[nn,2,1] - AX[i,pp])) * 0.5 + abs((PPP[nn,2,1] - AX[i,pp])*(PPP[nn,3,2] - AY[i,pp]) - (PPP[nn,2,2] - AY[i,pp])*( PPP[nn,3,1] - AX[i,pp])) * 0.5 + abs((PPP[nn,3,1] - AX[i,pp])*( PPP[nn,4,2] - AY[i,pp]) - (PPP[nn,3,2] - AY[i,pp])*( PPP[nn,4,1] - AX[i,pp])) * 0.5 + abs((PPP[nn,4,1] - AX[i,pp])*( PPP[nn,1,2] - AY[i,pp]) - (PPP[nn,4,2] - AY[i,pp])*( PPP[nn,1,1] - AX[i,pp])) * 0.5 >= AREA[nn] + 0.1;

s.t. eq_BoutsidePRECTANGLEPPP {i in {1..Nfe}, pp in {1..Nv}, nn in {1..Nobs}}:
abs((PPP[nn,1,1] - BX[i,pp])*( PPP[nn,2,2] - BY[i,pp]) - (PPP[nn,1,2] - BY[i,pp])*(PPP[nn,2,1] - BX[i,pp])) * 0.5 + abs((PPP[nn,2,1] - BX[i,pp])*(PPP[nn,3,2] - BY[i,pp]) - (PPP[nn,2,2] - BY[i,pp])*( PPP[nn,3,1] - BX[i,pp])) * 0.5 + abs((PPP[nn,3,1] - BX[i,pp])*( PPP[nn,4,2] - BY[i,pp]) - (PPP[nn,3,2] - BY[i,pp])*( PPP[nn,4,1] - BX[i,pp])) * 0.5 + abs((PPP[nn,4,1] - BX[i,pp])*( PPP[nn,1,2] - BY[i,pp]) - (PPP[nn,4,2] - BY[i,pp])*( PPP[nn,1,1] - BX[i,pp])) * 0.5 >= AREA[nn] + 0.1;

s.t. eq_CoutsidePRECTANGLEPPP {i in {1..Nfe}, pp in {1..Nv}, nn in {1..Nobs}}:
abs((PPP[nn,1,1] - CX[i,pp])*( PPP[nn,2,2] - CY[i,pp]) - (PPP[nn,1,2] - CY[i,pp])*(PPP[nn,2,1] - CX[i,pp])) * 0.5 + abs((PPP[nn,2,1] - CX[i,pp])*(PPP[nn,3,2] - CY[i,pp]) - (PPP[nn,2,2] - CY[i,pp])*( PPP[nn,3,1] - CX[i,pp])) * 0.5 + abs((PPP[nn,3,1] - CX[i,pp])
The current one is shown in the figure:
![c0f124e49b29ad8b76e595d8d969129](https://github.com/ampl/mp/assets/133726843/507f928a-34be-4893-a835-ff4f9cc13518)
![08ae903d00f469d3107a7e7cabae2b9](https://github.com/ampl/mp/assets/133726843/4d96d302-1e44-494c-889b-edcac19d7e09)
r4.run :
reset;
model M4.mod;
include ig.INIVAL;
option solver ipopt;
solve;

**Comment by glebbelov** [comment]
Ipopt does not use MP. Still, can you provide a complete, ideally small, example reproducing the problem?

**Comment by glebbelov** [comment]
Or at least, full output from the solver.

With Ipopt, a common issue is that it needs a good starting point where it can compute derivatives. Set variable values with `let {i in ITEMS} x[i] := 0.5;` or whatever values are reasonable.

**Comment by Anastasialiyu** [comment]
When the folder containing the code contains the original ipopt.exe, libhsl.dll, and libipoptfort.dll files, running the code in MATLAB  works fine for r1.run, r2.run, (r1.run, r2.run are not changed). 
However, when I delete those files from the folder or replace them with my own downloaded versions of ipopt.exe, libhsl.dll, and libipoptfort.dll from AMPL, even r1.run and r2.run give the following error: "Error at _cmdno 4952 executing 'solve' command: can't open C:\Users\ANASTA~1\AppData\Local\Temp\at21828.sol".

**Comment by glebbelov** [comment]
Please post the issue at https://discuss.ampl.com/.

**Comment by Anastasialiyu** [comment]
OK, Thank you.
