### ISSUE TITLE
Ctrl-C in Linux (and maybe MacOS)

### ISSUE THREAD

**Issue by glebbelov** [ampl/mp#223]
When running gurobi (MP) from AMPL, Ctrl-C causes `<BREAK>` and no current solution is saved.

*Current workaround*: send SIGINT to the Gurobi process.

When running from command line, Ctrl-C works as expected.

- [x] Possible reason: AMPL converts SIGINT to something else and MP does not handle it.

- [ ] Windows said to be ok --- check

**Comment by gomfy** [comment]
- [x] **Values in `ampl` after interrupt**
I've observed that when terminating the solver using `SIGINT (2)`, a solution file is successfully created. However, I have a query regarding scenarios where the solver is interrupted before finding a feasible solution. In such cases, it appears that none of the values are returned to `ampl`, and all variables retain their initial state. Is that supposed to be that way?

- [x] **Response to other signals**
Additionally, I've noticed that while Gurobi handles `SIGINT (2)` effectively, it does not seem to respond similarly to `SIGTERM (15)`. Specifically, no `.sol` file is written when `SIGTERM (15)` is used for termination: 
![image](https://github.com/ampl/mp/assets/35667347/27b9a9eb-3b32-4f3d-bbef-db9023be9374)
![image](https://github.com/ampl/mp/assets/35667347/73484c46-5269-4a5f-8bb9-8ee1b58548bd)

**Comment by glebbelov** [comment]
Reason: AMPL duplicates SIGINT, probably because some 3rd-party solvers ignore the 1st SIGINT (I remember reading this in some of Dave's notes.) MP forced _exit(1) after the 2nd signal. Changed this to be only after 3rd.

I assume without a feasible solution all variables should stay untouched, or as fixed by presolve - any thoughts how this should be otherwise?

Added SIGTERM.

I am closing the issue. Still to check in Mac/Win.
