### ISSUE TITLE
Unexpected solution returned from Gurobi?

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#226]
This Gurobi solve appears to give the correct result, where x and y are made as large as possible in order to minimize `x^(-0.3) * y^(-0.3)`:
```
ampl: var x >= 1, <= 3;
ampl: var y >= 11, <= 15;
ampl: minimize obj: x^(-0.3) * y^(-0.3);
ampl: option solver gurobi;
ampl: solve;
Gurobi 11.0.0: optimal solution; objective 0.3191804229
18 simplex iterations
1 branching nodes
 
ampl: display obj, x, y;
obj = 0.31918
x = 3
y = 15

ampl: display x^(-0.3) * y^(-0.3), (x*y)^(-0.3);
x^-0.3*y^-0.3 = 0.31918
(x*y)^-0.3 = 0.31918
```
If the objective is changed to the equivalent `(x*y)^(-0.3)`, Gurobi reports the same optimal objective value. But then it returns a different, suboptimal solution --- in fact it is the maximum:
```
ampl: var x >= 1, <= 3;
ampl: var y >= 11, <= 15;
ampl: minimize obj: (x*y)^(-0.3);
ampl: solve;
Gurobi 11.0.0: optimal solution; objective 0.3191804229
7 simplex iterations
1 branching nodes
 
------------ WARNINGS ------------
WARNING:  "Solution Check (Idealistic)"
     [ sol:chk:feastol=1e-06, :feastolrel=1e-06, :inttol=1e-05,
       :round='', :prec='' ]
Objective value violations:
  - 1 objective value(s) violated,
        up to 2E-01 (abs), up to 3E-01 (rel)
AMPL may evaluate constraints/objectives differently
than the solver, see mp.ampl.com/solution-check.html.
 
ampl: display obj, x, y;
obj = 0.48706
x = 1
y = 11

ampl: display x^(-0.3) * y^(-0.3), (x*y)^(-0.3);
x^-0.3*y^-0.3 = 0.48706
(x*y)^-0.3 = 0.48706
```
SCIP gets both solves right. Xpress, MOSEK, and HiGHS fail on this objective. (Maybe they just can't natively handle the ^ operator?)

**Comment by glebbelov** [comment]
The bug was in context propagation.

In the 2nd example, the ^ operator is in CTX_NEG (is minimized), but the function is monotone decreasing, so x*y should be in CTX_POS. Practically this means that the auxiliary variable `z == x*y` should be constrained as follows:
```ampl
  z <= x*y
```
and not as `z >= x*y`. Fixed.

BTW with SCIP the error occured too.

Xpress, MOSEK, and all other solvers do not handle non-convex quadratics.
