### ISSUE TITLE
OS X build fails

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#24]
Error:

```
/Users/travis/build/ampl/mp/test/../thirdparty/gtest/gtest.h:3204:10: error: invalid operands to binary expression ('std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >' and 'const std::__1::basic_ifstream<char, std::__1::char_traits<char> >')
    *ss_ << val;
    ~~~~ ^  ~~~
/Users/travis/build/ampl/mp/test/os-test.cc:309:50: note: in instantiation of function template specialization 'testing::Message::operator<<<std::__1::basic_ifstream<char, std::__1::char_traits<char> > >' requested here
      FAIL() << "Unexpected output from lsof:\n" << out
```

Build log: https://travis-ci.org/ampl/mp/jobs/47689898

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/a9049249d579b6270826287c7162ed47443a1716, but jacop-test fails:

```
27: Test command: /Users/travis/build/ampl/mp/bin/jacop-test
27: Test timeout computed to be: 9.99988e+06
27: No Java runtime present, requesting install.
27/29 Test #27: jacop-test .......................***Failed    0.05 sec
```

**Comment by vitaut** [comment]
This is Java bug http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7131356.

**Comment by vitaut** [comment]
Fixed.

**Comment by dpo** [comment]
Has this been fixed in the release? I'm having the same build issue.

**Comment by vitaut** [comment]
This is a Java bug on OS X and the workaround is to install `JavaForOSX2014-001.dmg` as it is done in the Travis build: https://github.com/ampl/mp/commit/9cae89647a2933025ad8035c9190f9fd9c7fc20d.

**Comment by vitaut** [comment]
Or you can simply disable the jacop module which is the only one using Java.

**Comment by dpo** [comment]
I haven't enabled any modules. The `README` says they're all disabled by default. Is that not the case?

**Comment by vitaut** [comment]
Sorry, I just realized that there are two issues here, the Java bug that causes `jacop-test` failure and the compile error and apparently we were talking about different issues =). The compile error fix is in master branch, but it hasn't been released yet.

**Comment by dpo** [comment]
Ok. Is [this](https://github.com/ampl/mp/commit/a9049249d579b6270826287c7162ed47443a1716) the patch?

**Comment by vitaut** [comment]
Yes
