### ISSUE TITLE
Option NLPHeur missing

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#241]
Dan Steffy at Gurobi has reported that an option in `gurobiasl` is missing from `gurobi` using MP:

> I am currently working with a Gurobi/AMPL customer. We found that setting the Gurobi parameter [NLPHeur](https://www.gurobi.com/documentation/current/refman/nlpheur.html)=0 is very important for the performance of this customer's model. However, it appears that this parameter is missing from the list of parameters that can be set when calling Gurobi through AMPL.

Currently the workaround is to treat `NLPHeur` as undocumented and to specify it using the `tech:optionnative` option.

**Comment by mapgccv** [comment]
Fixed in 200b260 and released as gurobi20240808
