### ISSUE TITLE
Gurobi option InfUnbdInfo

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/mp#244]
A user is looking for Gurobi parameter [InfUnbdInfo](https://www.gurobi.com/documentation/current/refman/infunbdinfo.html) which seems to be new in version 11 but not supported yet in AMPL's `gurobi_options`. (I can't find it anywhere in the release notes, actually.) Is it present in some form, or can it be added?

As a workaround, I have suggested to the user to try `optionnative="InfUnbdInfo 1"` .

**Comment by glebbelov** [comment]
`InfUnbdInfo=1` is set automatically whenever `alg:rays` is non-zero, with `alg:rays` described as follows:

```
alg:rays (rays)
      Whether to return suffix .unbdd if the objective is unbounded or suffix
      .dunbdd if the constraints are infeasible:

      0 - Neither
      1 - Just .unbdd
      2 - Just .dunbdd
      3 - Both (default)
```

And these suffixes are all what `InfUnbdInfo` is good for. (We can add text saying that `.dunbdd` is the Farkas dual.)

We can add a synonym option `alg:infunbdinfo`, which when set to 1, would mean `alg:rays=3` for example.
