### ISSUE TITLE
Dynamic library on OSX

### ISSUE THREAD

**Issue by dpo** [ampl/mp#26]
Is there support for dynamic libraries on OSX? `make install` only produces `.a`s.

**Comment by vitaut** [comment]
It should be possible to build shared libraries on OS X and other platforms by setting the [BUILD_SHARED_LIBS](http://www.cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) CMake variable to `True`:

```
$ cmake -DBUILD_SHARED_LIBS=True ...
```

That said, I only tried it on Linux so if you have any issues with this on OS X feel free to reopen this issue.
