### ISSUE TITLE
Matlab interface not installed

### ISSUE THREAD

**Issue by dpo** [ampl/mp#27]
I'm building the Matlab interface with `-DMATLAB_MEX=/path/to/mex` on OSX. The interface is being built, but `make install` seems to ignore it.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/cd355836364705c04c7627c04c506da6320daf57. Thanks for reporting!

**Comment by dpo** [comment]
I think there's another issue with the naming of the MEX files. `make install` says
````
CMake Error at src/asl/cmake_install.cmake:55 (file):
  file INSTALL cannot find
  "/tmp/ampl-mp-NOSSl2/mp-1.3.0/bin/amplfunc.mexmac".
````
In the `bin` directory, there are
````
amplfunc.mexmac.mexmaci64
spamfunc.mexmac.mexmaci64
````
but no `*.mexmac`. They should probably be called `amplfunc.mexmaci64` and `spamfunc.mexmaci64` because those are the names Matlab will be looking for.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/c96b9198aed29545a06e6123f6a2d940e1c7c128, thanks!
