### ISSUE TITLE
C wrapper for Julia

### ISSUE THREAD

**Issue by mlubin** [ampl/mp#28]
Continuing the discussion from dpo/ampl.jl#6, what's the best way to integrate @dpo's ``jampl.c/jampl.h`` into mp? Was going to submit a pull request, but it wasn't clear where the files should go or how to integrate them into the build system.

**Comment by dpo** [comment]
I'm happy to take care of the PR.

**Comment by vitaut** [comment]
Since it's ASL-related, I suggest putting the files in [src/asl](https://github.com/ampl/mp/tree/master/src/asl) and including them in `libasl`. I guess Julia doesn't have facilities for automatically creating bindings from header files, so there is no point in putting `jampl.j` in the include directory.

**Comment by mlubin** [comment]
Right, Julia has no need for the header file (but I could imagine that others may want it).

**Comment by vitaut** [comment]
For other uses it can be installed alongside ASL headers in `include/asl`.

**Comment by tkelman** [comment]
Bump. I'm about to submit my ampl-mp package to the official MinGW repository on the opensuse build service, which will make Windows binaries easily available to Julia packages via WinRPM, but makes it a little more time-consuming to update things. I can hold off and wait for a future version that will include these wrapper API's if they will be ready any time soon, but it will hold up my packaging of the latest Ipopt release.

**Comment by dpo** [comment]
All my generic functions are prefixed with `jampl_` because they were initially written for Julia. Should I change the prefix to `generic_` or something like that?

**Comment by vitaut** [comment]
I suggest using prefix `asl_` if it doesn't conflict with anything, since this API will go with the ASL even if it is not the part of the official ASL API. Does it make sense?

**Comment by dpo** [comment]
I placed `jampl.c` and `jampl.h` in `mp/src/asl`. When I build, the header file can't be found. `jampl.c` includes `jampl.h` and `jampl.h` includes `asl/asl_phfg.h`. How should I specify the include dirs?

**Comment by vitaut** [comment]
If you add `jampl.c` to the [`ASL_SOURCES`](https://github.com/ampl/mp/blob/master/src/asl/CMakeLists.txt#L223) CMake variable, it will be built as part of the `asl` target with ASL headers such as `asl_phfg.h` available without directory prefix:

```c++
#include "asl_phfg.h"
```

**Comment by dpo** [comment]
Ok thanks. What about `jampl.c`? It needs to include `jampl.h`, which I've also placed in `mp/src/asl` for the moment. How should I specify the path to that header file?

Also don't I need to add `jampl.c` to the `ASL_CORE_SOURCES`? Otherwise, it doesn't seem to make it to the shared library.

**Comment by vitaut** [comment]
Same thing,

```c++
#include "asl.h"
```
Since they are in the same directory there shouldn't be any problem.

> Also don't I need to add jampl.c to the ASL_CORE_SOURCES? Otherwise, it doesn't seem to make it to the shared library.

No, `ASL_CORE_SOURCES` is mainly for specifying relaxed compiler options for legacy code. I'll adjust the CMake script to use `ASL_SOURCES` for shared library too.

**Comment by dpo** [comment]
See #36.

**Comment by tkelman** [comment]
Thanks @dpo

**Comment by vitaut** [comment]
I've update the CMake config to include the new C interface in ASL: https://github.com/ampl/mp/commit/72f3e3af68eddeed56884c74d93775e1bb8dc69e

Thansk @dpo for contributing the code.

**Comment by dpo** [comment]
Thanks @vitaut. Does it also work with shared libs now? Are you planning on a new release soon?

**Comment by vitaut** [comment]
Yes, it works with with shared libs when configured with `BUILD_SHARED_LIBS`. I plan to do the next release in the beginning of March.

**Comment by vitaut** [comment]
@dpo I've just released a [new version of AMPL/MP](https://github.com/ampl/mp/releases/tag/2.0.0) which includes your C interface to ASL (thanks again for contributing). Sorry for the delay, had some other urgent work.
