### ISSUE TITLE
Non-executables are installed in `bin`

### ISSUE THREAD

**Issue by dpo** [ampl/mp#32]
On OSX, `make install` installs non-executables in `$PREFIX/bin`, e.g., the compiled MEX files, and some `dll`s. Is there a way to tell `cmake` to install those elsewhere?

**Comment by vitaut** [comment]
`dll`s should normally be installed in `bin`, because these are AMPL function libraries that must reside on the PATH for AMPL to find them. I am not familiar with the usual conventions for `mex` files, are these supposed to be installed in `lib`?

**Comment by tkelman** [comment]
mex files should probably go wherever shared libraries go, since that's all they are. So bin on Windows, lib on Unix would make sense to me.

**Comment by dpo** [comment]
Homebrew won't tolerate non-executables in `bin` or non-libraires in `lib`. I don't think it will consider `dll`s as libraries since those normally don't exist on OSX (in fact I don't understand why I'm getting `dll`s at all). The ideal would be to be able to specify where stuff should go, as `configure` lets you do, by specifying `bindir`, `libdir`, etc. Then in Homebrew, I'll be able to symlink things properly.

**Comment by tkelman** [comment]
There are cmake variables for most of this stuff. AMPL hardcodes some file names expecting these to be named dll and located in bin on all platforms (it's dlopening them, not linking to them), AIUI.

If you don't expect anyone to use the homebrew ASL version with a full install of AMPL, you can probably delete them.

**Comment by vitaut** [comment]
`.dll` is used for historical reasons and to keep scripts that use them identical on all platforms, these are ordinary `.so` files on Linux or `.dylib` files on OS X. There might be `bindir` and `libdir` equivalents in CMake, but I'm not aware of them.

I've changed the install directory for `.mex` files to follow the conventions used for shared libraries as suggested by @tkelman in https://github.com/ampl/mp/commit/f1e9cc37de56653c41a9866cf1c26a5b67055909.

**Comment by vitaut** [comment]
@dpo, I can add a CMake option to install AMPL function libraries in some other directory in case it helps. But then these libraries will have to be symlinked somewhere on the PATH for AMPL to be able to find these libraries.

**Comment by vitaut** [comment]
@tkelman AMPL function libraries can be used by solvers even if AMPL itself is not installed.

**Comment by tkelman** [comment]
Right, I do that with ASL reasonably often, but I don't think ASL is one of these always-`.dll` files we're talking about. Are the scripts that make the naming assumptions or code that's doing the dlopening in ASL, or some other component here or in the proprietary parts of AMPL?

**Comment by dpo** [comment]
Thanks @vitaut. If I install everything in `libexec`, then I can symlink what I need to keep homebrew happy.

**Comment by dpo** [comment]
See https://github.com/Homebrew/homebrew-science/pull/1796.

**Comment by vitaut** [comment]
I've added `AMPL_LIBRARY_DIR` CMake variable that allows you to specify the directory to install AMPL function libraries relative to `${CMAKE_INSTALL_PREFIX}`:

```
$ cmake -DAMPL_LIBRARY_DIR=libexec ...
```

@dpo, thanks a lot for your work on this!

@tkelman, no, ASL is not one of the `.dll` libraries. The code to read them is in ASL because solvers may rely on it. Unfortunately these naming assumptions are all over the place, in scripts, in ASL and, perhaps in AMPL, so we'll have to live with them (BTW I dislike this naming convention myself).

Closing for now. Feel free to reopen or open another issue if there are any other problems with this.

**Comment by dpo** [comment]
Thanks @vitaut. By the way, I just noticed that `jacpdim.h` isn't installed in `include/asl` (or anywhere else). Is that intentional?

**Comment by vitaut** [comment]
No, it's not intentional. Should be fixed in https://github.com/ampl/mp/commit/e983438e83680562e399b90aab25ba7395cf5d1c, thanks for catching this.
