### ISSUE TITLE
failure on cmake 2.8.11

### ISSUE THREAD

**Issue by mlubin** [ampl/mp#54]
cmake 2.8.11 is the latest version for which I could find a PPA which runs on travis. I get the following error trying to compile mp:

```
-- Build type: Release
-- Performing Test HAVE_STD_CPP11_FLAG
-- Performing Test HAVE_STD_CPP11_FLAG - Failed
-- Performing Test HAVE_STD_CPP0X_FLAG
-- Performing Test HAVE_STD_CPP0X_FLAG - Success
CMake Error at CMakeLists.txt:209 (target_compile_definitions):
  target_compile_definitions called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:243 (add_mp_library)
```
https://travis-ci.org/dpo/ampl.jl/jobs/61819188#L217
dpo/ampl.jl#7

**Comment by vitaut** [comment]
Thanks for the bug report. The minimum supported CMake version right now is 2.8.12 (I think I need to update `cmake_minimum_required`) because of `target_compile_options`. So I recommend using a recent version of CMake from [here](http://www.cmake.org/download/) instead of using a PPA.

**Comment by mlubin** [comment]
Okay, I got things working by just downloading the linux binary from the cmake page. You may want to bump the minimum version in ``CMakeLists.txt`` though.

**Comment by vitaut** [comment]
Great. Bumped the CMake version in https://github.com/ampl/mp/commit/466a6459caf67eed520fe09cfb9895cbffb6e7cf.
