### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by dpo** [ampl/mp#64]
The libraries in release 2.0.2 are still named `libasl.2.0.1.dylib` and `libmp.2.0.1.dylib` on OSX (haven't tested Linux).

Also https://github.com/ampl/mp/commit/5066e70e59d5640f78a19e985a0863f030b872fc didn't make it into the release. Will it make it into the next?

**Comment by vitaut** [comment]
> The libraries in release 2.0.2 are still named `libasl.2.0.1.dylib` and `libmp.2.0.1.dylib` on OSX (haven't tested Linux).

Oops, fixed in https://github.com/ampl/mp/commit/d33c3869a309d06b71e81e34b6fe4c84d7d0c991 and updated the release. Thanks for catching this.

> Also https://github.com/ampl/mp/commit/5066e70e59d5640f78a19e985a0863f030b872fc didn't make it into the release. Will it make it into the next?

Yes, https://github.com/ampl/mp/commit/5066e70e59d5640f78a19e985a0863f030b872fc will be a part of the next release.
