### ISSUE TITLE
Add pkg-config support

### ISSUE THREAD

**Issue by bchretien** [ampl/mp#68]
Supporting pkg-config makes it extremely easy and safe to use a given library, since finding the library on the system is simple, we get access to the proper compilation flags, the version number etc.

The idea would be to have a template file (e.g. [this one](https://github.com/open-source-parsers/jsoncpp/pull/42/files)) that would be filled with CMake variables (with [CONFIGURE_FILE](https://www.google.com/url?q=https://cmake.org/cmake/help/v3.2/command/configure_file.html&sa=U&ved=0CBkQFjABahUKEwijn-bDx7LIAhWD5aYKHTgDA4c&sig2=12xueAwm0EMffhs6GORSoQ&usg=AFQjCNEaiXO6NwJmbq5sgaHUsgtcKR_ACQ)). You can make something quite simple, like [here](https://github.com/open-source-parsers/jsoncpp/pull/42/files), or more [generic/complete](https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/pkg-config.pc.cmake) (this relies on our [custom CMake toolbox](https://github.com/jrl-umi3218/jrl-cmakemodules), but you can see the possibilities offered).

Then finding mp in CMake would look like:

```cmake
# Add pkg-config support in CMake
include(FindPkgConfig)

# Find mp
pkg_search_module(MP REQUIRED mp)
```

**Comment by vitaut** [comment]
Thank you for the suggestion. Unfortunately I won't have time to learn about and add `pkg-config` support myself (at least not in the nearest future), but patches are very welcome.

Note that it is already quite easy to use the library from another CMake-based project via `add_subdirectory` or as an external project.

**Comment by vitaut** [comment]
@bchretien Closing this for the reasons described above, but will be happy to accept a PR if you or anyone else is willing to implement `pkg-config` support.
