### ISSUE TITLE
function name collides with apple c++ library.

### ISSUE THREAD

**Issue by fqiang** [ampl/mp#72]
The following piece compiles error with clang on Mac version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

```cpp
#include <iostream>
using namespace std;
#include "asl.h"
#include <cstring>
int main(int argc, char **argv)
{
	FILE *nl;
	int i;
	char *fmt, *stub;
	cgrad *cg;
	ograd *og;
	real *b, *c;
	ASL *asl;

	if (argc < 2) {
		printf("Usage: %s stub\n", argv[0]);
		return 1;
		}


	asl = ASL_alloc(ASL_read_f);
	stub = argv[1];
	nl = jac0dim(stub, (fint)strlen(stub));

	f_read(nl,0);

	/* Print variable bounds and coefficients of first objective */

	c = (real *)Malloc(n_var*sizeof(real));
	for(i = 0; i < n_var; i++)
		c[i] = 0;
	if (n_obj)
		for(og = Ograd[0]; og; og = og->next)
			c[og->varno] = og->coef;
	printf("\nVariable\tlower bound\tupper bound\tcost\n");
	for(i = 0; i < n_var; i++)
		printf("%8d\t%-8g\t%-8g\t%g\n", i+1,
			LUv[2*i], LUv[2*i+1], c[i]);

	/* Print rows */

	b = LUrhs;
	for(i = 0; i < n_con; i++, b += 2) {
		printf("\nRow %d:", i+1);
		if (b[0] < b[1] && b[0] > negInfinity)
			printf(" %g <=", b[0]);
		fmt = " %g*X%d";
		for(cg = Cgrad[i]; cg; cg = cg->next, fmt = " + %g*X%d")
			printf(fmt, cg->coef, cg->varno+1);
		if (b[1] < Infinity) {
			printf(b[0] < b[1] ? " <= %g" : " == %g", b[1]);
			}
		printf("\n");
		}
	return 0;
	}
```

The compile error clang reports are 

clang++ -I/Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src -o CMakeFiles/updateFromAMPL.dir/lin1.C.o -c /Users/fqiang/workspace/PIPS/PIPS-NLP/Core/NlpInfo/lin1.C
In file included from /Users/fqiang/workspace/PIPS/PIPS-NLP/Core/NlpInfo/lin1.C:8:
In file included from /Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src/asl.h:86:
/Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src/funcadd.h:48:16: error: elaborated type refers to a
      template
typedef struct function function;
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_03:206:49: note: 
      declared here
template<class _Fp> class _LIBCPP_TYPE_VIS_ONLY function; // undefined
                                                ^
In file included from /Users/fqiang/workspace/PIPS/PIPS-NLP/Core/NlpInfo/lin1.C:8:
In file included from /Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src/asl.h:86:
/Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src/funcadd.h:77:2: error: reference to 'function' is
      ambiguous
        function *f;            /* for internal use by AMPL */
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__functional_03:206:49: note: 
      candidate found by name lookup is 'std::__1::function'
template<class _Fp> class _LIBCPP_TYPE_VIS_ONLY function; // undefined
                                                ^
/Users/fqiang/workspace/PIPS/ThirdPartyLibs/ASL/src/funcadd.h:48:16: note: candidate found by name lookup is
      'function'
typedef struct function function;
               ^

**Comment by vitaut** [comment]
The using directive introduces ambiguity by bringing `std::function` into the global namespace. To fix it just put the directive after the includes (which is a good idea anyway):

```c++
#include <iostream>
#include "asl.h"
#include <cstring>

using namespace std;
...
```
