### ISSUE TITLE
Don't run gen-expr-info at build time.

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#9]
Since expressions don't change often, it's probably OK to add expr-info.cc to the repo and possibly get rid of gen-expr-info.

**Comment by vitaut** [comment]
Hi @tkelman, did you have a chance to try this?

**Comment by tkelman** [comment]
no not yet, is there a tag that has this yet? or are you wanting to confirm the behavior works right before making the next tag?

**Comment by vitaut** [comment]
Yeah, although it doesn't matter at the moment whether you use `x86` or `x86_64`. The target pointer size is detected using different means.

**Comment by tkelman** [comment]
Looks really promising, I think we can close this resolved fixed. I'll leave another comment or open a new issue if I have any future problems.

Thanks, and belated happy new year!

**Comment by vitaut** [comment]
Cool, closing this issue then.
Happy new year to you too!

**Comment by tkelman** [comment]
Oh yeah, I guess if you feel so inclined you could tweak the Travis config to not install wine until it's time to run the tests, since it's no longer needed at build time.

**Comment by tkelman** [comment]
And see http://docs.travis-ci.com/user/multi-os/ if you might want to enable Travis for OSX. Would have to tweak things around a bit since you use `brew` instead of `apt-get` and would want to disable the cross-compile on Mac.

**Comment by vitaut** [comment]
Good idea. With wine installation postponed compile errors may appear earlier.
As for OSX build, I do plan to enable it. Already did it for another repo (cppformat).
