### ISSUE TITLE
Decouple problem and solver APIs

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#95]
This should go:

``` c++
  BasicProblem(const Solver &, fmt::StringRef) {}
```

**Comment by vitaut** [comment]
Removed the string argument in https://github.com/ampl/mp/commit/9335f7973cb587e9bd2b30ace958c3bdfb664f19.

**Comment by glebbelov** [comment]
Also this should go (in various places):

typename Solver::ProblemBuilder

A Solver should be ignorant of the Builder used (at least, for SRP). It seems a convenience typedef anyway.
