### ISSUE TITLE
smpswriter: invalid arguments to expectation

### ISSUE THREAD

**Issue by mapgccv** [ampl/mp#98]
After compiling a fresh version of smpswriter and following the instructions at https://github.com/ampl/mp/tree/master/solvers/smpswriter, I get:
```
ampl: shell "smpswriter farmer";
Error: invalid arguments to expectation
exit code 1
```

Besides, I have tried to change the objective function in `format.ampl` to the format shown in the page above - they are different, as in the page above the function `expectation` is not used, and I get the same error.
Any insight?

**Comment by vitaut** [comment]
The information https://github.com/ampl/mp/tree/master/solvers/smpswriter refers to the old SMPS writer which is available in the released version. Please refer to #97 for the current format.

**Comment by vitaut** [comment]
`smpswriter` is working now.
